name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Jalankan pipeline saat ada push ke branch main

jobs:
  # we dont install this, except there is tests, linting, etc
  # install:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.13

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  build_and_push_ecr:
    # needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  upload_to_s3:
    needs: build_and_push_ecr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip the application
        run: zip -r flask-app.zip .

      - name: Upload ZIP to S3
        run: |
          aws s3 cp flask-app.zip s3://${{ secrets.S3_BUCKET_NAME }}/flask-app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    needs: upload_to_s3
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Elastic Beanstalk Environment Configuration
        run: |
          echo "[
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"AWS_ACCESS_KEY_ID\",
              \"Value\": \"${{ secrets.AWS_ACCESS_KEY_ID }}\"
            },
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"AWS_SECRET_ACCESS_KEY\",
              \"Value\": \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"
            },
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"AWS_SESSION_TOKEN\",
              \"Value\": \"${{ secrets.AWS_SESSION_TOKEN }}\"
            },
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"AWS_REGION\",
              \"Value\": \"${{ secrets.AWS_REGION }}\"
            },
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"S3_BUCKET_NAME\",
              \"Value\": \"${{ secrets.S3_BUCKET_NAME }}\"
            },
            {
              \"Namespace\": \"aws:elasticbeanstalk:application:environment\",
              \"OptionName\": \"API_GATEWAY_URL\",
              \"Value\": \"${{ secrets.API_GATEWAY_URL }}\"
            }
          ]" > .ebenv.json

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label ${{ github.run_id }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=flask-app.zip \
            --process

          aws elasticbeanstalk update-environment \
            --option-settings file://.ebenv. \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label ${{ github.run_id }}

      - name: Check Elastic Beanstalk Health Status
        run: |
          aws elasticbeanstalk describe-environment-health \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --attribute HealthStatus --query "HealthStatus"
